Добавлены 2 файла
TonikX/ITMO_IMRIP_DataBases_2020 pull request #13
Opened 2020-04-22 19:31 UTC by artemkhtrn

Добавлены два файла: LR1_Khutorian_D41421.erwin Otchet_Khutorian_D41421.pdf

2020-05-05 09:34 UTC, TonikX requested changes
![image](https://user-images.githubusercontent.com/23614490/81052812-cc488a00-8ecc-11ea-94bf-7ec39ed3973d.png)

2020-05-08 09:05 UTC, artemkhtrn commented
Обновил модель и отчет.

2020-05-13 22:47 UTC, TonikX requested changes
Модель норм. Где типовые запросы и файл с моделью отдельно?

2020-05-14 08:03 UTC, artemkhtrn commented
Добавил в отчет типовые запросы и pdf файл с моделью отдельно.

2020-05-21 14:51 UTC, TonikX requested changes
Проверить внешние ключи в sql-файле.

2020-05-27 21:55 UTC, TonikX commented
Напоминаю.

2020-05-28 08:03 UTC, artemkhtrn commented
Изменил, @TonikX

2020-06-04 18:40 UTC, artemkhtrn commented
Отчет по Лабораторной работе №3

2020-06-16 09:27 UTC, TonikX approved these changes
Зачтено.

2020-06-16 09:27 UTC, merged