D41421 Мамонова Настя ЛР1
TonikX/ITMO_IMRIP_DataBases_2020 pull request #2
Opened 2020-04-21 10:04 UTC by amamonova

Сделана первая лабораторная работа, составлен отчет в pdf формате.

2020-05-01 09:09 UTC, TonikX requested changes
![image](https://user-images.githubusercontent.com/23614490/80795243-9cd00f80-8ba4-11ea-9be0-6ed2801034f5.png)

2020-05-05 09:33 UTC, TonikX commented
Отчет переделать забыли. Почитайте на странице репозитория, что должно быть отправлено сюда.

2020-05-07 19:03 UTC, amamonova commented
@TonikX добрый вечер! не могли бы Вы, пожалуйста, заапрувить (или нет) схему БД, так как я сижу над второй лабой и хотела бы ее сразу сделать верно

2020-05-13 21:52 UTC, TonikX approved these changes
Зачтено.

2020-05-13 21:53 UTC, merged