D41423 Xiao Nan LR2/LR1
TonikX/ITMO_IMRIP_DataBases_2020 pull request #26
Opened 2020-05-11 20:40 UTC by XiaoNan31

2020-05-21 00:29 UTC, TonikX requested changes
![image](https://user-images.githubusercontent.com/23614490/82510469-499e0c80-9b13-11ea-9073-cc6eecdd260c.png)

2020-06-16 09:09 UTC, TonikX commented
![image](https://user-images.githubusercontent.com/23614490/84755332-35daae80-afca-11ea-9126-6274fd2a3f98.png)

2020-06-16 11:53 UTC, XiaoNan31 commented
What you see is the original version of LR1, I'm sorry that I didn't delete it.Now I have deleted it, please check the modified LR1

2020-06-19 22:20 UTC, TonikX reviewed
Смотрел, смотрел... Завтра пришлю Вам переделанную работу)

2020-06-20 11:22 UTC, closed without merging

2020-06-20 11:24 UTC, XiaoNan31 commented
> Смотрел, смотрел... Завтра пришлю Вам переделанную работу)

Ok, I will wait, thanks.