Добавлены отчет и бд. Волков Дмитрий
TonikX/ITMO_IMRIP_DataBases_2020 pull request #3
Opened 2020-04-21 12:52 UTC by Dima1Volkov

2020-05-01 09:13 UTC, TonikX requested changes
![image](https://user-images.githubusercontent.com/23614490/80795440-297acd80-8ba5-11ea-8e9d-764213171302.png)

2020-05-05 09:36 UTC, TonikX reviewed
![image](https://user-images.githubusercontent.com/23614490/81052953-074abd80-8ecd-11ea-89bf-6cb3740c3054.png)

2020-05-05 17:24 UTC, Dima1Volkov reviewed
Исправил модель

2020-05-13 21:56 UTC, TonikX approved these changes
![image](https://user-images.githubusercontent.com/23614490/81869967-a3d02800-957d-11ea-9d2b-e8987ed8b79c.png)

2020-05-27 15:47 UTC, TonikX approved these changes
1, 2 зачтено.

2020-05-27 15:48 UTC, merged