Добавлена Лабораторная № 1 Новохацкой
TonikX/ITMO_IMRIP_DataBases_2020 pull request #4
Opened 2020-04-22 06:39 UTC by EseniiaNovo

Прикрепленные файлы: отчет в формате PDF, схема БД в формате PDF. Работа выполнена на онлайн платформе, ссылка на рабочую модель находится в отчете, в пункте № 4.

2020-04-25 08:57 UTC, TonikX requested changes
![image](https://user-images.githubusercontent.com/23614490/80275752-fbe8dc80-86eb-11ea-9ab8-c25664840dc4.png)

2020-05-01 09:56 UTC, EseniiaNovo commented
Исправленный вариант Лабораторной работы и Питер Чен загружены

2020-05-05 09:38 UTC, TonikX commented
Вы что-то изменили? я не нашел изменений в моделе.

2020-05-05 10:05 UTC, EseniiaNovo commented
Я загрузила на гит новые файлы, возможно сделала что-то не так при загрузке, раз их не видно. Но вот они
![Исправления_База учета выполненных работ рекламного агентства “Луч”](https://user-images.githubusercontent.com/56360925/81055315-1f244080-8ed1-11ea-8809-51509eb4fbc4.png)
![Lab 1_Питер Чен](https://user-images.githubusercontent.com/56360925/81055322-20556d80-8ed1-11ea-892e-0ec32dc52166.png)

2020-05-05 10:08 UTC, EseniiaNovo commented
Через view file у меня все исправления открываются
![Снимок экрана 2020-05-05 в 13 12 01](https://user-images.githubusercontent.com/56360925/81055507-7b876000-8ed1-11ea-8502-87d8896e52ba.png)

2020-05-13 21:57 UTC, TonikX commented
Судя по всему, в отчете старая модель. Поправьте.

2020-05-14 06:43 UTC, EseniiaNovo commented
Загрузила исправленный отчет

2020-05-14 06:47 UTC, EseniiaNovo commented
И загружена вторая лабораторная

2020-05-27 15:19 UTC, TonikX approved these changes
Первые две принял.

2020-05-27 15:19 UTC, merged