Были добавлены файлы lab1.pdf, lab1v1.erwin, отчет_lab1
TonikX/ITMO_IMRIP_DataBases_2020 pull request #8
Opened 2020-04-22 12:32 UTC by heyitscarin

Были добавлены файлы lab1.pdf, lab1v1.erwin, отчет_lab1

2020-05-01 09:23 UTC, TonikX requested changes
![image](https://user-images.githubusercontent.com/23614490/80795899-80cd6d80-8ba6-11ea-9289-095da1959e6c.png)

2020-05-05 09:42 UTC, TonikX requested changes
![image](https://user-images.githubusercontent.com/23614490/81053491-d15a0900-8ecd-11ea-878b-4a6fb1a2a5cf.png)

2020-05-08 08:24 UTC, heyitscarin commented
Обновила файлы с исправлениями lab1model, lab1v1(updated), OtchetVasileva_lab1(updated)

2020-05-13 22:00 UTC, TonikX approved these changes
1, 2 - зачтено.

2020-05-13 22:00 UTC, merged